// lib/posts/index.ts
//
// AUTO-GENERATED by scripts/generate-blog.mjs — DO NOT EDIT MANUALLY.
// Each new post gets its own file in this directory. Run the generator to add posts.

import legacyPosts from './legacy'

// Individual post imports
import post_post_10_browser_security_extensions_everyone_should_install from './10-browser-security-extensions-everyone-should-install'
import post_api_security_for_browser_tab_extension_developers from './api-security-for-browser-tab-extension-developers'
import post_browser_extension_permissions_the_hidden_security_risk_youre_ignoring from './browser-extension-permissions-the-hidden-security-risk-youre-ignoring'
import post_browser_sandbox_escapes_what_they_are_and_why_you_should_care from './browser-sandbox-escapes-what-they-are-and-why-you-should-care'
import post_browser_security_on_a_schedule_how_time_based_tab_locking_works from './browser-security-on-a-schedule-how-time-based-tab-locking-works'
import post_how_browser_tab_sync_across_devices_creates_new_attack_surfaces from './how-browser-tab-sync-across-devices-creates-new-attack-surfaces'
import post_how_passkeys_are_replacing_passwords_and_why_tab_protection_still_matters from './how-passkeys-are-replacing-passwords-and-why-tab-protection-still-matters'
import post_how_webauthn_and_fido2_biometrics_are_changing_browser_security from './how-webauthn-and-fido2-biometrics-are-changing-browser-security'
import post_mastering_referrer_policy_a_technical_guide_to_controlling_information_leaks_from_your_browser from './mastering-referrer-policy-a-technical-guide-to-controlling-information-leaks-from-your-browser'
import post_screen_recording_protection_hiding_tabs_from_screen_captures from './screen-recording-protection-hiding-tabs-from-screen-captures'
import post_social_engineering_attacks_through_browser_tabs_how_to_defend from './social-engineering-attacks-through-browser-tabs-how-to-defend'
import post_the_anatomy_of_a_phishing_page_how_attackers_clone_legitimate_sites_in_your_browser from './the-anatomy-of-a-phishing-page-how-attackers-clone-legitimate-sites-in-your-browser'
import post_webrtc_ip_leak_how_video_calls_expose_your_real_ip_address_through_the_browser from './webrtc-ip-leak-how-video-calls-expose-your-real-ip-address-through-the-browser'

export const allPosts = [
    ...legacyPosts,
    post_post_10_browser_security_extensions_everyone_should_install,
    post_api_security_for_browser_tab_extension_developers,
    post_browser_extension_permissions_the_hidden_security_risk_youre_ignoring,
    post_browser_sandbox_escapes_what_they_are_and_why_you_should_care,
    post_browser_security_on_a_schedule_how_time_based_tab_locking_works,
    post_how_browser_tab_sync_across_devices_creates_new_attack_surfaces,
    post_how_passkeys_are_replacing_passwords_and_why_tab_protection_still_matters,
    post_how_webauthn_and_fido2_biometrics_are_changing_browser_security,
    post_mastering_referrer_policy_a_technical_guide_to_controlling_information_leaks_from_your_browser,
    post_screen_recording_protection_hiding_tabs_from_screen_captures,
    post_social_engineering_attacks_through_browser_tabs_how_to_defend,
    post_the_anatomy_of_a_phishing_page_how_attackers_clone_legitimate_sites_in_your_browser,
    post_webrtc_ip_leak_how_video_calls_expose_your_real_ip_address_through_the_browser,
]
