// lib/posts/index.ts
//
// AUTO-GENERATED by scripts/generate-blog.mjs — DO NOT EDIT MANUALLY.
// Each new post gets its own file in this directory. Run the generator to add posts.

import legacyPosts from './legacy'

// Individual post imports
import post_incognito_mode_wont_save_you_the_case_for_real_tab_level_privacy from './incognito-mode-wont-save-you-the-case-for-real-tab-level-privacy'

export const allPosts = [
    ...legacyPosts,
    post_incognito_mode_wont_save_you_the_case_for_real_tab_level_privacy,
]
