export default function Features() {
  const features = [
    { icon: "🛡️", title: "Privacy Blur Shield", desc: "Automatically hides passwords, credit cards, emails, OTPs, and other sensitive information on web pages. It can also blur the page when you switch windows or step away.", gradient: "from-indigo-500 to-purple-500" },
    { icon: "⏱️", title: "Auto-Lock Timer", desc: "Lock tabs after you have been inactive. Choose 1–480 minutes, and smart activity detection avoids interrupting video playback.", gradient: "from-indigo-500 to-violet-500" },
    { icon: "📅", title: "Scheduled Locking", desc: "Automatically lock tabs during chosen days and hours, including overnight schedules. Great for work hours or sleep time.", gradient: "from-emerald-500 to-teal-500" },
    { icon: "⌨️", title: "Keyboard Shortcuts", desc: "Use Alt+Shift+9 to lock the active tab, Alt+Shift+0 to open the manager, Alt+Shift+8 to lock all tabs, and Alt+Shift+7 to toggle Stealth Mode. Shortcuts are customizable; free users get 3 Lock All uses and Pro is unlimited. Locked tabs show a lock icon and badge counter.", gradient: "from-violet-500 to-purple-500" },
    { icon: "🌐", title: "Domain Lock", desc: "Lock an entire website or its subdomains with wildcard patterns. New matching tabs are protected automatically.", gradient: "from-blue-500 to-cyan-500" },
    { icon: "🔐", title: "One-Click Locking", desc: "Protect any tab instantly with one click. No complicated setup is needed.", gradient: "from-cyan-500 to-teal-500" },
    { icon: "👆", title: "Biometric Unlock", desc: "Unlock protected tabs with Windows Hello, Touch ID, Face ID, Android biometrics, or USB security keys. Your biometric data never leaves your device, and your master password remains a fallback.", gradient: "from-violet-500 to-indigo-500" },
    { icon: "🖱️", title: "Right-Click Context Menus", desc: "Lock a tab, lock a domain, lock all tabs, or toggle Stealth Mode from the right-click menu. Works on pages, links, images, and selected text.", gradient: "from-indigo-500 to-violet-500" },
    { icon: "🕵️", title: "Stealth Mode", desc: "Hide the lock count and silence notifications. Locked tabs can appear as a fake browser error page. Toggle from the popup, Alt+Shift+7, or right-click.", gradient: "from-purple-500 to-violet-500" },
    { icon: "🎨", title: "Light / Dark Theme", desc: "Choose light or dark mode from the popup header. Your choice stays in sync across Locksy pages and the lock screen without a reload.", gradient: "from-cyan-500 to-violet-500" },
    { icon: "📸", title: "Webcam Intruder Capture", desc: "Silently capture a local webcam snapshot when someone repeatedly fails to unlock a protected tab. Review and delete attempts from the dedicated local log.", gradient: "from-rose-500 to-red-500" },
    { icon: "🚀", title: "Startup Session Lock", desc: "Automatically protect tabs restored when the browser starts, including pages that finish restoring shortly after launch. Requires Locksy Pro.", gradient: "from-amber-500 to-yellow-500" },
    { icon: "📊", title: "Weekly Privacy Reports", desc: "Review local lock history, failed snooper attempts, and security scores for the last 7 days. Reports are generated completely offline.", gradient: "from-violet-600 to-indigo-600" },
    { icon: "💬", title: "Custom Lock Screen Messages", desc: "Display personalized notes, reminders, or warning messages directly on the lock screen to deter snoopers.", gradient: "from-teal-500 to-emerald-500" },
    { icon: "🔓", title: "1-Click Unlock All", desc: "Unlock all currently protected tabs at once by entering your master password once. Useful when resuming a workflow.", gradient: "from-amber-500 to-orange-500" },
    { icon: "🚨", title: "Real-Time Intruder Alerts", desc: "Get browser notifications and visual warnings on the lock screen when someone attempts to access protected tabs.", gradient: "from-rose-500 to-red-500" },
    { icon: "🔒", title: "PBKDF2 Key Derivation", desc: "Password protection uses 600k iterations with SHA-256 and follows the stated OWASP 2023 configuration. The implementation is designed to make password cracking much harder.", gradient: "from-purple-500 to-pink-500" },
    { icon: "🛡️", title: "Rate Limiting & Brute-Force Protection", desc: "Slows repeated password guesses and adds timing-attack protection to make automated cracking attempts harder.", gradient: "from-amber-500 to-orange-500" },
    { icon: "🔑", title: "Incognito Mode Support", desc: "Use Locksy in private browsing windows with the same tab protection.", gradient: "from-green-500 to-emerald-500" },
    { icon: "🔐", title: "8+ Security Layers", desc: "Multiple protection mechanisms work together to help prevent bypass attempts.", gradient: "from-red-500 to-rose-500" },
    { icon: "📴", title: "100% Offline", desc: "Locksy keeps its security processing and stored protection data on your device rather than sending it to a server.", gradient: "from-indigo-500 to-blue-500" },
    { icon: "🚫", title: "No Account Required", desc: "Install Locksy and start protecting tabs without creating an account.", gradient: "from-orange-500 to-red-500" },
  ]

  return (
    <section id="features" className="py-24 md:py-32 bg-gradient-to-b from-background via-accent/30 to-background relative overflow-hidden">
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] dark:bg-[linear-gradient(to_right,#ffffff08_1px,transparent_1px),linear-gradient(to_bottom,#ffffff08_1px,transparent_1px)] bg-[size:4rem_4rem]" />
      <div className="absolute inset-0 pointer-events-none overflow-hidden"><div className="absolute top-1/4 left-1/5 w-96 h-96 bg-primary/8 dark:bg-primary/15 rounded-full blur-3xl animate-pulse" /><div className="absolute bottom-1/3 right-1/4 w-80 h-80 bg-secondary/8 dark:bg-secondary/15 rounded-full blur-3xl animate-pulse delay-700" /></div>
      <div className="relative max-w-7xl mx-auto px-4 md:px-6">
        <div className="text-center mb-20"><div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full text-sm font-medium text-primary backdrop-blur-sm mb-6"><span aria-hidden="true">✨</span>Powerful Features</div><h2 className="section-title">Everything You Need.<br />Nothing You Don't.</h2><p className="section-subtitle">Protect sensitive tabs with a full set of privacy, locking, automation, and security tools.</p></div>
        <div className="grid md:grid-cols-3 gap-8">{features.map((feature, idx) => <div key={idx} className="group feature-card relative overflow-hidden"><div className={`absolute inset-0 bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-5 transition-opacity duration-500`} /><div className="relative z-10"><div className={`inline-flex w-16 h-16 items-center justify-center text-4xl mb-6 bg-gradient-to-br ${feature.gradient} rounded-2xl shadow-lg group-hover:scale-110 transition-transform duration-500`}><span aria-hidden="true">{feature.icon}</span></div><h3 className="font-bold text-xl mb-3 text-foreground group-hover:text-primary transition-colors">{feature.title}</h3><p className="text-muted-foreground leading-relaxed">{feature.desc}</p></div><div className={`absolute top-0 right-0 w-20 h-20 bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-10 blur-2xl transition-opacity duration-500`} /></div>)}</div>
      </div>
    </section>
  )
}
