import { writeFileSync, readdirSync } from 'fs'
import { join, dirname, basename } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const POSTS_DIR = join(__dirname, '..', 'lib', 'posts')
const INDEX_PATH = join(POSTS_DIR, 'index.ts')

const individualFiles = readdirSync(POSTS_DIR)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts' && f !== 'legacy.ts')
    .sort()

const toVarName = (f) => {
    const raw = basename(f, '.ts').replace(/-/g, '_')
    const safe = raw.replace(/[^a-zA-Z0-9_]/g, '')
    if (!safe) throw new Error(`Cannot derive a safe variable name from filename: "${f}"`)
    return /^[0-9]/.test(safe) ? `post_${safe}` : safe
}

const importLines = individualFiles
    .map(f => {
        const name = toVarName(f)
        return `import post_${name} from './${basename(f, '.ts')}'`
    })
    .join('\n')

const entryLines = individualFiles
    .map(f => `    post_${toVarName(f)},`)
    .join('\n')

const indexContent = `// lib/posts/index.ts
//
// AUTO-GENERATED by scripts/generate-blog.mjs — DO NOT EDIT MANUALLY.
// Each new post gets its own file in this directory. Run the generator to add posts.

// Individual post imports
${importLines}

export const allPosts = [
${entryLines}
]
`

writeFileSync(INDEX_PATH, indexContent, 'utf-8')
console.log(`Successfully synced lib/posts/index.ts with ${individualFiles.length} posts.`)
